//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NodeXL.GraphGallery.WcfService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationInformation", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.NodeXL.GraphGallery.WcfService")]
    public partial class RegistrationInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string RegistrationKeyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationKey
        {
            get
            {
                return this.RegistrationKeyField;
            }
            set
            {
                this.RegistrationKeyField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="INodeXLGraphGalleryService")]
public interface INodeXLGraphGalleryService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraphResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraphStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    void AddGraph(string title, string author, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraphResponse")]
    System.Threading.Tasks.Task AddGraphAsync(string title, string author, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraphWithCredentials", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraphWithCredentialsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraphWithCredentialsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    void AddGraphWithCredentials(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraphWithCredentials", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraphWithCredentialsResponse")]
    System.Threading.Tasks.Task AddGraphWithCredentialsAsync(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph3", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraph3Response")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph3StringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    void AddGraph3(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, string graphML);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph3", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraph3Response")]
    System.Threading.Tasks.Task AddGraph3Async(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, string graphML);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph4", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraph4Response")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph4StringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    void AddGraph4(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph4", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraph4Response")]
    System.Threading.Tasks.Task AddGraph4Async(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph5", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraph5Response")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph5StringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    void AddGraph5(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped, byte[] brandImage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/AddGraph5", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/AddGraph5Response")]
    System.Threading.Tasks.Task AddGraph5Async(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped, byte[] brandImage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/Register", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/RegisterResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/INodeXLGraphGalleryService/RegisterStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
    Microsoft.NodeXL.GraphGallery.WcfService.RegistrationInformation Register(string email, string productKey, string uniqueID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/Register", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/RegisterResponse")]
    System.Threading.Tasks.Task<Microsoft.NodeXL.GraphGallery.WcfService.RegistrationInformation> RegisterAsync(string email, string productKey, string uniqueID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/GetTestString", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/GetTestStringResponse")]
    string GetTestString(int numberToIncludeInString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeXLGraphGalleryService/GetTestString", ReplyAction="http://tempuri.org/INodeXLGraphGalleryService/GetTestStringResponse")]
    System.Threading.Tasks.Task<string> GetTestStringAsync(int numberToIncludeInString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INodeXLGraphGalleryServiceChannel : INodeXLGraphGalleryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NodeXLGraphGalleryServiceClient : System.ServiceModel.ClientBase<INodeXLGraphGalleryService>, INodeXLGraphGalleryService
{
    
    public NodeXLGraphGalleryServiceClient()
    {
    }
    
    public NodeXLGraphGalleryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NodeXLGraphGalleryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NodeXLGraphGalleryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NodeXLGraphGalleryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddGraph(string title, string author, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML)
    {
        base.Channel.AddGraph(title, author, description, spaceDelimitedTags, fullSizeImage, thumbnail, graphML);
    }
    
    public System.Threading.Tasks.Task AddGraphAsync(string title, string author, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML)
    {
        return base.Channel.AddGraphAsync(title, author, description, spaceDelimitedTags, fullSizeImage, thumbnail, graphML);
    }
    
    public void AddGraphWithCredentials(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML)
    {
        base.Channel.AddGraphWithCredentials(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, graphML);
    }
    
    public System.Threading.Tasks.Task AddGraphWithCredentialsAsync(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, string graphML)
    {
        return base.Channel.AddGraphWithCredentialsAsync(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, graphML);
    }
    
    public void AddGraph3(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, string graphML)
    {
        base.Channel.AddGraph3(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, workbook, workbookSettings, graphML);
    }
    
    public System.Threading.Tasks.Task AddGraph3Async(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, string graphML)
    {
        return base.Channel.AddGraph3Async(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, workbook, workbookSettings, graphML);
    }
    
    public void AddGraph4(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped)
    {
        base.Channel.AddGraph4(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, workbook, workbookSettings, graphMLZipped);
    }
    
    public System.Threading.Tasks.Task AddGraph4Async(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped)
    {
        return base.Channel.AddGraph4Async(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, workbook, workbookSettings, graphMLZipped);
    }
    
    public void AddGraph5(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped, byte[] brandImage)
    {
        base.Channel.AddGraph5(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, workbook, workbookSettings, graphMLZipped, brandImage);
    }
    
    public System.Threading.Tasks.Task AddGraph5Async(string title, string author, string password, string description, string spaceDelimitedTags, byte[] fullSizeImage, byte[] thumbnail, byte[] workbook, string workbookSettings, byte[] graphMLZipped, byte[] brandImage)
    {
        return base.Channel.AddGraph5Async(title, author, password, description, spaceDelimitedTags, fullSizeImage, thumbnail, workbook, workbookSettings, graphMLZipped, brandImage);
    }
    
    public Microsoft.NodeXL.GraphGallery.WcfService.RegistrationInformation Register(string email, string productKey, string uniqueID)
    {
        return base.Channel.Register(email, productKey, uniqueID);
    }
    
    public System.Threading.Tasks.Task<Microsoft.NodeXL.GraphGallery.WcfService.RegistrationInformation> RegisterAsync(string email, string productKey, string uniqueID)
    {
        return base.Channel.RegisterAsync(email, productKey, uniqueID);
    }
    
    public string GetTestString(int numberToIncludeInString)
    {
        return base.Channel.GetTestString(numberToIncludeInString);
    }
    
    public System.Threading.Tasks.Task<string> GetTestStringAsync(int numberToIncludeInString)
    {
        return base.Channel.GetTestStringAsync(numberToIncludeInString);
    }
}
